---
name: Init Workflow

on:
  workflow_call:
    inputs:
      prerelease:
        description: 'Is this a Pre-Release?'
        required: true
        type: string
      release:
        description: 'Is this a Release?'
        required: true
        type: string

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: |
          echo "prerelease?: ${{ inputs.prerelease }}"
          echo "release?: ${{ inputs.release }}"

      - name: conditinal test
        run: |
          if [[ ${{ inputs.prerelease }} == true ]];
          then
            echo "Prerelease (inputs) is: ${{ inputs.prerelease }}"
          fi
          if [[ ${{ env.DBUI_RELEASE }} == true ]];
          then echo "Prerelease (inputs) is: ${{ inputs.release }}"
          fi

      - name: Another TEST
        if: ${{ inputs.prerelease == 'true' }}
        run: |
          echo "another prerelease?: ${{ inputs.prerelease }}"
          echo "another release?: ${{ inputs.release }}"

      - name: Another TEST 2
        if: inputs.release == 'true'
        run: |
          echo "another 2 prerelease?: ${{ inputs.prerelease }}"
          echo "another 2 release?: ${{ inputs.release }}"

      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ Checkout repo
        uses: actions/checkout@v3

      - name: ðŸ”„ Init Cache
        uses: ./.github/actions/npm-cache
        id: 'npm-cache' # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: ðŸ“¥ Download deps default-npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
