name: Leaked Secrets Scan

on:
  workflow_call:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: â†” Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: ğŸ· TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.7.3
        with:
          path: ./
          base: ${{ steps.extract_branch.outputs.branch }}
          head: HEAD

      - name: ğŸ’€ Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
