name: Build Stencil Local

on:
  workflow_call:

jobs:
  build-stencil:
    name: Build Stencil Local
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      - name: ğŸ”¨ Build Stencil Local
        run: npm run build.local --workspace=@db-ui/elements

      - name: â¬†ï¸Upload Stencil Local
        uses: actions/upload-artifact@v3
        with:
          name: stencil-local
          path: packages/db-ui-elements-stencil
