---
name: Get and save latest tag

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      tag:
        description: 'Latest git tag'
        value: ${{ jobs.publish.outputs.tag }}

jobs:
  publish:
    name: Get and save latest tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extractTag.outputs.tag }}
    steps:
      - name: â¬‡ Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: â†” Extract tag name
        shell: bash
        run: echo "tag=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_OUTPUT
        id: extractTag

      - name: ðŸ’€ Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
