---
name: Deploy to gh-pages

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ‚¨á Checkout repo
        uses: actions/checkout@v3

      - name: üîÑ Init Cache
        uses: ./.github/actions/npm-cache

      - name: ‚¨á Download build
        uses: ./.github/actions/download-tar-artifact
        with:
          name: build
          path: out

      - name: ‚ûï Bundle current gh-pages
        uses: ./.github/actions/bundle-gh-page

      - name: ü•Ö Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: üñ®Ô∏è Print gh-pages url
        run: |
          export BRANCH=${GITHUB_REF#refs/heads/}
          if ${{ env.RELEASE == "true" }}
          then
            export URL=https://db-ui.github.io/elements
          elif [ ${{ ! -d env.VALID_SEMVER_VERSION }} ];
          then
            export URL=https://db-ui.github.io/elements/version/${{ inputs.tag }}
          else
            export URL=https://db-ui.github.io/elements/review/${BRANCH}
          fi
          echo "URL: $URL"
          echo "### GH-Pages URL :rocket: <br> <br> $URL" >> $GITHUB_STEP_SUMMARY
